### PR TITLE
#33 - added thanks to and slack logo

### PR DESCRIPTION
**Pull request by tmoran18**

### CODE REVIEW

**Comment by tomahawk-pilot** [comment]
can you share a screenshot

**Comment by tmoran18** [comment]
screenshot

**Comment by tomahawk-pilot** [comment]
can you share the new screeshot or link to your github pages

**Comment by tmoran18** [comment]
Apologies, I am quite new to contributing.
Can you be a little more specific in how mean divide up into frames? The twitter widget, hack and slack are all made up of col-2's within the Hacktober ID.

Then once that done you want me to publish that branch to github pages so I can provide a live link?

**Pull request closed without merging**
